name: Build Images

on:
  release:
    types: [created]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      version-patch: ${{ steps.set-version.outputs.patch }}
      version-minor: ${{ steps.set-version.outputs.minor }}
      version-major: ${{ steps.set-version.outputs.major }}
    steps:
      - uses: actions/checkout@v4

      - name: Get release version
        id: set-version
        run: |
          # Strip the 'v' prefix from the tag
          PATCH_VERSION="${GITHUB_REF#refs/tags/v}"
          MINOR_VERSION="${PATCH_VERSION%.*}"
          MAJOR_VERSION="${MINOR_VERSION%.*}"

          echo "patch=${PATCH_VERSION}" >> $GITHUB_OUTPUT
          echo "minor=${MINOR_VERSION}" >> $GITHUB_OUTPUT
          echo "major=${MAJOR_VERSION}" >> $GITHUB_OUTPUT

      - name: Discover container images for build matrix
        id: set-matrix
        run: |
          DIRS=$(find . -name Dockerfile -exec dirname {} \; | sed 's|^./||' | grep -v '^_base-image$' | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${DIRS}" >> $GITHUB_OUTPUT

  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: _base-image
          push: true
          tags: ghcr.io/hologit/lenses/base:node-20
          cache-from: type=registry,ref=ghcr.io/hologit/lenses/base:node-20
          cache-to: type=inline

  build-lens:
    needs: [discover, build-base]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image }}
          push: true
          tags: |
            ghcr.io/hologit/lenses/${{ matrix.image }}:latest
            ghcr.io/hologit/lenses/${{ matrix.image }}:${{ needs.discover.outputs.version-major }}
            ghcr.io/hologit/lenses/${{ matrix.image }}:${{ needs.discover.outputs.version-minor }}
            ghcr.io/hologit/lenses/${{ matrix.image }}:${{ needs.discover.outputs.version-patch }}
          cache-from: type=registry,ref=ghcr.io/hologit/lenses/${{ matrix.image }}:latest
          cache-to: type=inline
